### ISSUE TITLE
统一代码风格

### ISSUE THREAD

**Issue by RecursiveG** [InfinityStudioSingularity/Singularity#2]
感觉有必要统一一下代码风格
- 缩进4个空格
- 行尾LF换行
- UTF-8编码
- 首字母小写驼峰命名法
- 使用Java7

应该需要各位调教一下自己的IDE
各位意见如何?

**Comment by LasmGratel** [comment]
已经是基本统一的了，不过@DarkHighness 是大写命名，，Java那个可以不用管，我们没有Lambda等j8特性

**Comment by RecursiveG** [comment]
因为我之前在改的时候发现CRLF换行和LF换行混合....
所以统一起见还是改成LF换行好了...其他应该没什么问题...
@LasmGratel
